version: '3.8'

services:
  nc2parquet:
    build: .
    container_name: nc2parquet
    volumes:
      - ./examples:/home/nc2parquet/examples:ro
      - ./output:/home/nc2parquet/output
      - ~/.aws:/home/nc2parquet/.aws:ro  # Mount AWS credentials
    environment:
      - RUST_LOG=info
      - AWS_REGION=us-east-1
    command: ["--help"]

  nc2parquet-dev:
    build:
      context: .
      target: builder
    container_name: nc2parquet-dev
    volumes:
      - .:/usr/src/nc2parquet
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/nc2parquet/target
    working_dir: /usr/src/nc2parquet
    environment:
      - RUST_LOG=debug
      - CARGO_HOME=/usr/local/cargo
    command: ["cargo", "test"]

  # LocalStack for S3 testing
  localstack:
    image: localstack/localstack:2.0
    container_name: nc2parquet-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  cargo-cache:
  target-cache: